config/routes.rb
Rails3BootstrapDeviseCancan::Application.routes.draw do
  resources :comments 

  get "comments/create"

  get "comment/destroy"

  get "like/like"

  #resources :shots
    
  match "shots/index/:user" => "shots#index", :as => :indexshots
  match "shots/like/:shot_id" => "shots#like", :as => :likeshot
  match "shots/dislike/:shot_id" => "shots#dislike", :as => :dislikeshot
  match "shots/add_tag" => "shots#add_tag", :as => :add_tag

  get "like/dislike"

  resources :shots

  match "users/follow/:following" => "users#follow", :as => :follow
  match "users/unfollow/:unfollowing" => "users#unfollow", :as => :unfollow

  authenticated :user do
    root :to => 'shots#index'
  end
  root :to => "shots#index"
  devise_for :users do
    get "/users/sign_out" => "devise/sessions#destroy", :as => :destroy_user_session
  end
  resources :users, :only => [:show, :index]
end

app/models/shot.rb
class Shot < ActiveRecord::Base
  attr_accessible :caption, :description, :likes, :user_id, :shot
  has_attached_file :shot, :styles => { :medium => "400x300>", :thumb => "100x100>" }

  acts_as_taggable_on :tags #:colors, :themes

  acts_as_likeable

  belongs_to :user
  has_many :comments
end

app/controllers/shots_controller.rb
class ShotsController < ApplicationController

require 'will_paginate/array'

  # GET /shots
  # GET /shots.json
  def index
    @title = "recent shots"
    tag = params[:tag]
    user = params[:user]
    like = params[:likes]
    if tag
      @title = "Tag: " + tag
      @shots = Shot.tagged_with(tag).paginate(:page => params[:page], :per_page => 12)
    else 
      if user 
        @title = User.find(user).name + " shots."
        @shots = Shot.find_all_by_user_id(user).paginate(:page => params[:page], :per_page => 12)
      else 
        @shots = Shot.all.paginate(:page => params[:page], :per_page => 12)
      end
    end 
    if like
      @title = "This is what " + User.find(user).name + " likes."
      likes = Like.find_all_by_user_id(user)
      @shots = []
      likes.each{|l|
        @shots << Shot.find(l.shot_id)
      }
      @shots = @shots.paginate
    end
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @shots }
    end
  end

  # GET /shots/1
  # GET /shots/1.json
  def show
    @shot = Shot.find(params[:id])
    @comment = Comment.new
    @comments = @shot.comments

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @shot }
    end
  end

  # GET /shots/new
  # GET /shots/new.json
  def new
    @shot = Shot.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @shot }
    end
  end

  # GET /shots/1/edit
  def edit
    @shot = Shot.find(params[:id])
  end

  # POST /shots
  # POST /shots.json
  def create
    @shot = Shot.new(params[:shot])
    @shot.user_id = current_user.id

    respond_to do |format|
      if @shot.save
        format.html { redirect_to @shot, notice: 'Shot was successfully created.' }
        format.json { render json: @shot, status: :created, location: @shot }
      else
        format.html { render action: "new" }
        format.json { render json: @shot.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /shots/1
  # PUT /shots/1.json
  def update
    @shot = Shot.find(params[:id])

    respond_to do |format|
      if @shot.update_attributes(params[:shot])
        format.html { redirect_to @shot, notice: 'Shot was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @shot.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shots/1
  # DELETE /shots/1.json
  def destroy
    @shot = Shot.find(params[:id])
    @shot.destroy

    respond_to do |format|
      format.html { redirect_to shots_url }
      format.json { head :no_content }
    end
  end

  def like  
    shot = Shot.find(params[:shot_id])
    @like = Like.new()
    @like.shot_id = shot.id
    @like.user_id = current_user.id
    
    respond_to do |format|
      if @like.save
        shot.likes = shot.likes + 1 
        shot.save
        format.html { redirect_to shot }
        format.json { render json: shot, status: :liked, location: @shot }
      else
        format.html { render action: "show" }
        format.json { render json: shot.errors, status: :unprocessable_entity }
      end
    end
  end

  def dislike  
    shot = Shot.find(params[:shot_id])
    @like = Like.find_by_user_id_and_shot_id(current_user, shot.id)
    @like.destroy
    shot.likes = shot.likes - 1
    shot.save
    
    respond_to do |format|
      format.html { redirect_to shot }
      format.json { head :no_content }
      end
  end

  def add_tag
    tags = params[:tag].split
    shot = Shot.find(params[:shot_id])
    current_user.tag(shot, :with => tags, :on => :tags)
    #shot.tag_list << tags
    shot.save 
    redirect_to shot
  end
end

app/helpers/shots_helper.rb
module ShotsHelper

  def currentUserLikes(shot)
    if Like.find_by_user_id_and_shot_id(current_user.id, shot.id)
      return true 
    else
      return false
    end
  end

end

app/views/shots/_form.html.erb
<%= form_for(@shot) do |f| %>
  <% if @shot.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@shot.errors.count, "error") %> prohibited this shot from being saved:</h2>

      <ul>
      <% @shot.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :caption %><br />
    <%= f.text_field :caption %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :photo %><br />
    <%= f.file_field :shot %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/shots/crop.html.erb
<% content_for(:head) do %>
<%= stylesheet_link_tag "jquery.Jcrop" %>
<%= javascript_include_tag "jquery.Jcrop.min" %>
<script type="text/javascript" charset="utf-8">
$(function() {
  $('#cropbox').Jcrop({
    onChange: update_crop,
    onSelect: update_crop,
    setSelect: [0, 0, 500, 500],
    aspectRatio: 1
  });
});

function update_crop(coords) {
  var rx = 100/coords.w;
  var ry = 100/coords.h;
  $('#preview').css({
    width: Math.round(rx * <%= @shot.shot_geometry(:large).width %>) + 'px',
    height: Math.round(ry * <%= @shot.shot_geometry(:large).height %>) + 'px',
    marginLeft: '-' + Math.round(rx * coords.x) + 'px',
    marginTop: '-' + Math.round(ry * coords.y) + 'px'
  });
  var ratio = <%= @shot.shot_geometry(:original).width %> / <%= @shot.shot_geometry(:large).width %>;
  $("#crop_x").val(Math.round(coords.x * ratio));
  $("#crop_y").val(Math.round(coords.y * ratio));
  $("#crop_w").val(Math.round(coords.w * ratio));
  $("#crop_h").val(Math.round(coords.h * ratio));
}
</script>
<% end %>

<%= image_tag @shot.shot.url(:large), :id => "cropbox" %>

<h4>Preview:</h4>
<div style="width:100px; height:100px; overflow:hidden">
  <%= image_tag @shot.shot.url(:large), :id => "preview" %>
</div>

<% form_for @shot do |f| %>
  <% for attribute in [:crop_x, :crop_y, :crop_w, :crop_h] %>
    <%= f.hidden_field attribute, :id => attribute %>
  <% end %>
  <p><%= f.submit "Crop" %></p>
<% end %>" %>
<% content_for(:head) do %>
<%= stylesheet_link_tag "jquery.Jcrop" %>
<%= javascript_include_tag "jquery.Jcrop.min" %>
<script type="text/javascript" charset="utf-8">
$(function() {
  $('#cropbox').Jcrop({
    onChange: update_crop,
    onSelect: update_crop,
    setSelect: [0, 0, 500, 500],
    aspectRatio: 1
  });
});

function update_crop(coords) {
  var rx = 100/coords.w;
  var ry = 100/coords.h;
  $('#preview').css({
    width: Math.round(rx * <%= @shot.shot_geometry(:large).width %>) + 'px',
    height: Math.round(ry * <%= @shot.shot_geometry(:large).height %>) + 'px',
    marginLeft: '-' + Math.round(rx * coords.x) + 'px',
    marginTop: '-' + Math.round(ry * coords.y) + 'px'
  });
  var ratio = <%= @shot.shot_geometry(:original).width %> / <%= @shot.shot_geometry(:large).width %>;
  $("#crop_x").val(Math.round(coords.x * ratio));
  $("#crop_y").val(Math.round(coords.y * ratio));
  $("#crop_w").val(Math.round(coords.w * ratio));
  $("#crop_h").val(Math.round(coords.h * ratio));
}
</script>
<% end %>

<%= image_tag @shot.shot.url(:large), :id => "cropbox" %>

<h4>Preview:</h4>
<div style="width:100px; height:100px; overflow:hidden">
  <%= image_tag @shot.shot.url(:large), :id => "preview" %>
</div>

<% form_for @shot do |f| %>
  <% for attribute in [:crop_x, :crop_y, :crop_w, :crop_h] %>
    <%= f.hidden_field attribute, :id => attribute %>
  <% end %>
  <p><%= f.submit "Crop" %></p>
<% end %>

app/views/shots/edit.html.erb
<h1>Editing shot</h1>

<%= render 'form' %>

<%= link_to 'Show', @shot %> |
<%= link_to 'Back', shots_path %>

app/views/shots/index.html.erb
<h1><%=h @title %></h1>
<br>
<div class="row-fluid">
  <div class="span8">
    <% i = 0 %>
    <% @shots.each do |shot| %>
      <% if i%3 == 0 %>
    <div class="row-fluid">
      <% end %>    
      <% i = i + 1%>
      <div class="span4" align = "center">
        <%= image_tag shot.shot.url(:medium)%> <%=h link_to shot.caption, shot %>
      </div> <!-- span4 -->
      <% if i%3 == 0 %>
    </div> <!--fin row--></br>
      <% end %>
    <% end %>
    <% if i%3 != 0 %>
</div> <!--fin row--></br>
    <% end %>
  </div> <!-- span 8-->

  <div class="span4" align = "center">
    Extra 
  </div>
</div>

<br />
<% if user_signed_in?%>
  <%= link_to 'New Shot', new_shot_path %>
<% end %>

<div class="digg_pagination" align = "center"> 
    <div clas="page_info">
      <%= page_entries_info @shots %>
    </div>
    <%= will_paginate @shots, :container => false %>
</div>

app/views/shots/new.html.erb
<h1>New shot</h1>

<%= render 'form' %>

<%= link_to 'Back', shots_path %>

app/views/shots/show.html.erb
<p id="notice"><%= notice %></p>

<h3>
  <%= @shot.caption %>
</h3>

<p>
  by:  <%= link_to @shot.user.name, @shot.user%>
</p>
<div class="row-fluid">
  <div class="span6">

    <br>
    <div align = "center">
      <%= image_tag @shot.shot.url(:medium) %>
    </div>
  </div>

  <div class="span6">
    <p>
<br>
      <b>Description:</b>
      <%= @shot.description %>
    </p>
    <p>
      <b>Likes:</b>
      <%= @shot.likes %>
    </p>

    <div class="row-fluid">
      <%= link_to image_tag("FaceBookIcon.png"), 'http://www.facebook.com/sharer.php?u='+request.fullpath, :target => :blank %>
      <% if user_signed_in? %>
        <% if currentUserLikes(@shot) %>
          <%= link_to "Dislike!", dislikeshot_path(@shot.id)%>
        <% end %>

        <% if !currentUserLikes(@shot) %>
          <%= link_to "Like!", likeshot_path(@shot.id)%>
        <% end %>
      <% end %>



      <%= tweet_button(:via => "ShotBox", :count=>"none", :text => "Look at this amazing Shot at @ShotBox")%>
    </div>
<br/>

    <% if @shot.tag_list.size > 0 %>
      Tags: 
        <% @shot.tags.each do |t| %>
          <%= link_to t.name, :action => "index", :tag => t.name %> 
        <% end %>
      <br \>
    <% end %>

    <% if @shot.user == current_user%>
      <b>Add new tag (separated by white spaces)</b>
        <%= form_tag '/shots/add_tag' do %>
          <%=label_tag 'name' %>
          <%=text_field_tag 'tag'%>
          <%= hidden_field_tag(:shot_id, @shot.id) %>

          <div><%= submit_tag 'Add' %></div>
        <% end %>
    <% end %>

    <% @comments.each do |c|%>
      <p><%=h c.user.name %> said:</p>
      <p>&nbsp;&nbsp;&nbsp;<%=h c.text%> 
      <% if c.user == current_user || c.shot.user == current_user%>
         <%= link_to("Delete", c, :method => :delete, :confirm => "Do you really wanna delete this comment?")%></p> 
      <% end %>
      
    <% end %>

    <% if user_signed_in? %>
      <%= form_for @comment do |f| %>
        <%= f.label :Comment %>
        <%= f.text_area :text, :cols => 30, :rows => 3%><br />

        <%= hidden_field_tag(:shot_id, @shot.id) %>

        <%= f.submit %>
      <% end %>
    <% end %>
  </div>
</div>
<br>
<div align = "center">
  <%= link_to 'Edit', edit_shot_path(@shot) %> |
  <%= link_to 'Back', shots_path %>
</div>