config/routes.rb
Rails3BootstrapDeviseCancan::Application.routes.draw do
  resources :comments 

  get "comments/create"

  get "comment/destroy"

  get "like/like"

  #resources :shots
    
  match "shots/index/:user" => "shots#index", :as => :indexshots
  match "shots/like/:shot_id" => "shots#like", :as => :likeshot
  match "shots/dislike/:shot_id" => "shots#dislike", :as => :dislikeshot
  match "shots/add_tag" => "shots#add_tag", :as => :add_tag

  get "like/dislike"

  resources :shots

  match "users/follow/:following" => "users#follow", :as => :follow
  match "users/unfollow/:unfollowing" => "users#unfollow", :as => :unfollow

  authenticated :user do
    root :to => 'shots#index'
  end
  root :to => "shots#index"
  devise_for :users do
    get "/users/sign_out" => "devise/sessions#destroy", :as => :destroy_user_session
  end
  resources :users, :only => [:show, :index]
end

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
    <a class="close" data-dismiss="alert">&#215;</a>
    <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
  </div>
<% end %>

app/views/layouts/_navigation.html.erb
<%= link_to "ShotBox", root_path, :class => 'brand' %>
<ul class="nav">
  <% if user_signed_in? %>
    <li>
      <%= link_to 'My shots', indexshots_path(current_user) %>        
    </li>
    <li>
    <%= link_to 'Logout', destroy_user_session_path, :method=>'delete' %>        
    </li>
  <% else %>
    <li>
    <%= link_to 'Login', new_user_session_path %>  
    </li>
  <% end %>
  <% if user_signed_in? %>
    <li>
    <%= link_to 'Edit account', edit_user_registration_path %>
    </li>
    <% if current_user.has_role? :admin %>
      <li>
      <%= link_to 'Admin', users_path %>
      </li>
    <% end %>
  <% else %>
    <li>
    <%= link_to 'Sign up', new_user_registration_path %>
    </li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!doctype html>
<html>
  <head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title><%= content_for?(:title) ? yield(:title) : "ShotBox" %></title>
    <meta name="description" content=""/>
    <meta name="author" content=""/>
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "jquery-rails" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body>
    <header class="navbar navbar-fixed-top">
      <nav class="navbar-inner">
        <div class="container">
          <%= render 'layouts/navigation' %>
        </div>
      </nav>
    </header>
    <div id="main" role="main">
      <div class="container">
        <div class="content">
           <div class="row">
            <div class="span12">
              <%= render 'layouts/messages' %>
              <%= yield %>
            </div>
          </div>
          <footer>
          </footer>
        </div>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
  </body>
</html>